### ISSUE TITLE
Insert signatures without `rpmsign`

### ISSUE THREAD

**Issue by puiterwijk** [puiterwijk/rpm-head-signing#1]
At this moment, the signature insertion is being handled by using `rpmsign` and then just `cp` as the gpg command.
It would be great if we could instead just get the RPM sighdr, insert it in there, and then save that.

That would bring us a step closer to not even needing the full RPM on the box that executed this part of the process (since we upload just the sighdr to Koji).
If this is in place, we could add an endpoint to Koji to get just the sigheader/header part of an RPM, and never need the full RPM.

**Comment by iamamoose** [comment]
This is also needed as older RPM versions create a v3 signature by default, which can't work with this method of header signing, and they have no option to not create a v3 signature.

**Comment by puiterwijk** [comment]
For information: I was waiting to fix this until I had tests in place, to ensure that my changes wouldn't break things (and I didn't have to manually test everything).
Given that I just merged a test suite, I hope to work on this shortly.
